# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [4]:
np_array = np.array([0,0,0,0,0,0,0,0,0,0])

#### Create an array of 10 fives

In [5]:
np_array = np.array([5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [6]:
int_array = np.arange(10,51)
int_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
even_array =  np.arange(10,51,2)
even_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix = np.arange(0,9).reshape(3,3)

matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [16]:
identity_matrix = np.identity(3, dtype=int)

identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [20]:
random_number = np.random.rand()
random_number

0.5077350585190263

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
random_number_25 = np.random.rand(25)
random_number_25

array([0.85495507, 0.64388571, 0.59257624, 0.86440459, 0.67318292,
       0.21643764, 0.06015473, 0.30339758, 0.51579807, 0.99346856,
       0.31245002, 0.78938942, 0.75730451, 0.28010909, 0.84107091,
       0.98786109, 0.49753549, 0.69603332, 0.68860411, 0.16402202,
       0.66465016, 0.76056468, 0.71077942, 0.65038278, 0.17212363])

#### Create the following matrix:

#Shape and Size Functions
shape: Returns the shape (dimensions) of the array.

size: Returns the total number of elements in the array.

ndim: Returns the number of dimensions of the array.



**2. Reshaping Functions**


1.   reshape: Reshapes the array into a specified shape.
2.   flatten: Converts a multi-dimensional array into a 1D array.




**3. Mathematical Functions**
sum: Returns the sum of all elements or along an axis.

1.   sum: Returns the sum of all elements or along an axis
2.   mean: Calculates the mean of elements.

max, min: Returns the maximum or minimum value in the array.




#Shape and Size Functions
shape: Returns the shape (dimensions) of the array.
size: Returns the total number of elements in the array.



**4. Array Manipulation Functions**
append: Appends values to the array (creates a new array).

delete: Deletes elements from the array (creates a new array).

transpose or .T: Transposes the array.

## 6. Logical Operations
where: Returns indices where a condition is true.

**7. Sorting and Searching**
sort: Sorts the elements.

**### Now do the following**

Copying
copy: Creates a copy of the array.

Random Functions (from numpy.random)
rand, randint: Generates random numbers.

In [36]:
matrix = np.random.rand(3,3)

matrix

array([[0.13696016, 0.85510773, 0.27454392],
       [0.8402728 , 0.14005231, 0.54037496],
       [0.2302092 , 0.97607581, 0.07185632]])

In [38]:
arr1 = matrix

arr2 = arr1.copy()

arr2

array([[0.13696016, 0.85510773, 0.27454392],
       [0.8402728 , 0.14005231, 0.54037496],
       [0.2302092 , 0.97607581, 0.07185632]])

In [39]:
np.random.rand(3)


array([0.99893839, 0.09692159, 0.72675076])

In [27]:
np.random.rand(2,2)

array([[0.93539745, 0.54605248],
       [0.25075029, 0.1058547 ]])

In [29]:
np.random.randint(1,10, size = 5)

array([6, 3, 8, 3, 8])

#### Get the sum of all the values in arr

In [40]:
sum_array = np.sum(arr1)

sum_array

np.float64(4.065453203243088)

#### Get the standard deviation of the values in arr

In [41]:
std_array = np.std(arr1)

std_array

np.float64(0.33623222386677487)

#### Get the sum of all the columns in arr

In [ ]:
# prompt: Get the sum of all the columns in arr

sum_of_columns = np.sum(arr1, axis=0)
sum_of_columns


In [42]:
sum_col = np.sum(arr1, axis = 0)

sum_col

array([1.20744216, 1.97123585, 0.88677519])

# Great Job!